#pragma once

#define DISPLAY_ST7789
#define DISPLAY_COLOR_BITS 16
#define DISPLAY_RES_WIDTH 240
#define DISPLAY_RES_HEIGHT 280
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 20
#define DISPLAY_TOUCH_ENABLED 1
