#pragma once

enum MXFontSize {
  MX_FONT_SIZE_14 = 14,
  MX_FONT_SIZE_16 = 16,
  MX_FONT_SIZE_18 = 18,
  MX_FONT_SIZE_20 = 20,
  MX_FONT_SIZE_24 = 24,
  MX_FONT_SIZE_30 = 30,
  MX_FONT_SIZE_36 = 36,
  MX_FONT_SIZE_48 = 48,
};

#define MX_FONT_SIZE_SM MX_FONT_SIZE_14
#define MX_FONT_SIZE_DEFAULT MX_FONT_SIZE_16
#define MX_FONT_SIZE_LG MX_FONT_SIZE_18
#define MX_FONT_SIZE_XL MX_FONT_SIZE_20
#define MX_FONT_SIZE_2XL MX_FONT_SIZE_24
#define MX_FONT_SIZE_3XL MX_FONT_SIZE_30
#define MX_FONT_SIZE_4XL MX_FONT_SIZE_36
#define MX_FONT_SIZE_5XL MX_FONT_SIZE_48
