#pragma once

#define DISPLAY_ST77916
#define DISPLAY_COLOR_BITS 16
#define DISPLAY_RES_WIDTH 360
#define DISPLAY_RES_HEIGHT 360
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_TOUCH_ENABLED 1
